### PR TITLE
Handle exit status from the CLI class

### LINKED ISSUE #183: stack_master --version returns a failed exit code
Is this intended?  Not critical, but a little bizarre.

```
arecker@localhost:testproj$ be stack_master --version
StackMaster 0.16.0
arecker@localhost:testproj$ echo $?
1
```

### PR DESCRIPTION
**Pull request by orien**
### Context

There are a couple of peculiar StackMaster behaviours regarding exit status.

- `stack_master --version` results in a status of `1` (#183).
- The exit status is set in the `stack_master` binstub, but the Cucumber feature suite doesn't test this. It drives StackMaster via the `StackMaster::CLI` class directly. This makes validating the status code impossible.

### Change

I propose we move handling of the exit status into the `StackMaster::CLI` class. This will solve both problems:

- Running `stack_master --version` will return a status of `0` (fixes #183).
- The Cucumber test suite will accurately validate the exit status of each command. I've added this validation to all scenarios.

### CODE REVIEW

File: bin/stack_master [hunk 1]
```diff
@@ -10,8 +10,7 @@ end
 trap("SIGINT") { raise StackMaster::CtrlC }
 
 begin
-  result = StackMaster::CLI.new(ARGV.dup).execute!
-  exit !!result
+  StackMaster::CLI.new(ARGV.dup).execute!
```
Comment (orien) [inline bin/stack_master]: This binstub no longer handles the exit status.

File: lib/stack_master/cli.rb [hunk 2]
```diff
@@ -253,7 +253,7 @@ def execute_stacks_command(command, args, options)
           end
         end
       end
-      success
+      @kernel.exit false unless success
```
Comment (orien) [inline lib/stack_master/cli.rb]: The `CLI` class now handles the exit status.

File: features/version.feature [hunk 3]
```diff
@@ -0,0 +1,4 @@
+Feature: Check the StackMaster version
+  Scenario: Use the --version option
+    When I run `stack_master --version`
+    Then the exit status should be 0
```
Comment (orien) [inline features/version.feature]: Add a scenario to ensure `stack_master --version` results in a `0` status.

File: features/apply.feature [hunk 4]
```diff
@@ -123,6 +123,7 @@ Feature: Apply command
       | +    "Vpc": {                                                                  |
       | Parameters diff:                                                               |
       | KeyName: my-key                                                                |
+    And the exit status should be 0
```
Comment (orien) [inline features/apply.feature]: Validate the exit status in all Cucumber scenarios.

File: features/apply_with_allowed_accounts.feature [hunk 5]
```diff
@@ -43,7 +43,7 @@ Feature: Apply command with allowed accounts
     And I run `stack_master apply us-east-1 myapp-db`
     And the output should contain all of these lines:
       | Account '11111111' is not an allowed account. Allowed accounts are ["22222222"].|
-    Then the exit status should be 0
+    Then the exit status should be 1
```
Comment (orien) [inline features/apply_with_allowed_accounts.feature]: This is an example of an incorrect Cucumber validation. This scenario was ensuring a status `0`, but because it was only testing via the `CLI` class it missed the binstub returning `1`.

Now the feature correctly checks the value return in the command invocation.

Note: this is not a change in StackMaster behaviour.
